spring:
  application:
    name: bills-collector
  datasource:
    username: postgres
    password: some-cool-password
    url: jdbc:postgresql://localhost:5432/bills-collector
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog.yaml

server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}
